name: 'Flutter Outdated & Vulnerable Packages Report'
description: 'Generates Flutter/Dart outpdated and vulnerable packages reports'
inputs:
  reports-directory:
    description: 'Folder to store the reports'
    required: false
    default: 'reports'
  working-directory:
    description: 'Working directory for action'
    default: '.'
runs:
  using: "composite"
  steps:
      - uses: QuickBirdEng/actions/setup-flutter@main
        with:
          setup-gems: true
          working-directory: ${{ inputs.working-directory }}
      - shell: bash
        run: cp $GITHUB_ACTION_PATH/scripts/* .
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.7'
      - name: Install dependencies
        shell: bash
        run: go install github.com/google/osv-scanner/cmd/osv-scanner@latest
      - name: Run OSV-Scanner
        shell: bash
        run: osv-scanner --version
      - shell: bash
        run: |
          project_path=`pwd`/${{ inputs.working-directory }}
          bash generate_flutter_report.sh --project-path=$project_path --reports-path=$project_path/${{ inputs.reports-directory }}
      - uses: actions/upload-artifact@v4
        with:
          name: reports-flutter
          path: ${{ inputs.working-directory }}/${{ inputs.reports-directory }}
          retention-days: 90
