name: 'Flutter Outdated & Vulnerable Packages Report'
description: 'Generates Flutter/Dart outpdated and vulnerable packages reports'
inputs:
  reports-dir:
    description: 'Folder to store the reports'
    required: false
    default: 'reports'
runs:
  using: "composite"
  steps:
      - uses: QuickBirdEng/actions/setup-flutter@main
        with:
          setup-gems: true
      - shell: bash
        run: cp $GITHUB_ACTION_PATH/scripts/* .
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.7'
      - name: Install dependencies
        shell: bash
        run: go install github.com/google/osv-scanner/cmd/osv-scanner@latest
      - name: Run OSV-Scanner
        shell: bash
        run: osv-scanner --version
      - shell: bash
        run: bash generate_flutter_report.sh --project-path=`pwd` --reports-path=`pwd`/${{ inputs.reports-dir }}
      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ${{ inputs.reports-dir }}
