name: 'Flutter Outdated & Vulnerable Packages Report'
description: 'Generates Flutter/Dart outpdated and vulnerable packages reports'
inputs:
  reports-directory:
    description: 'Folder to store the reports'
    required: false
    default: 'reports'
  working-directory:
    description: 'Working directory for action'
    default: '.'
  is-library:
    description: 'Do not setup iOS if library'
    default: false
  report-name:
    description: 'Name to use for uploaded report'
    type: string
    required: false
    default: reports-flutter
runs:
  using: "composite"
  steps:
      - if: ${{ inputs.is-library == false }}
        uses: QuickBirdEng/actions/setup-fastlane@main
        with:
          platform: flutter
          working-directory: ${{ inputs.working-directory }}
      - uses: QuickBirdEng/actions/setup-flutter@main
        with:
          setup-gems: ${{ inputs.is-library == false }}
          working-directory: ${{ inputs.working-directory }}
      - shell: bash
        run: cp $GITHUB_ACTION_PATH/scripts/* .
      - shell: bash
        run: |
          project_path=`pwd`/${{ inputs.working-directory }}
          bash generate_flutter_report.sh --project-path=$project_path --reports-path=$project_path/${{ inputs.reports-directory }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.report-name }}
          path: ${{ inputs.working-directory }}/${{ inputs.reports-directory }}
          retention-days: 90
