name: 'Dependency Review Assignment'
description: 'Assign reviewers based on dependency changes'
inputs:
  project-type:
    description: 'The type of project (e.g., web, flutter or * for both)'
    required: true
    default: '*'
  soup-approvers:
    description: 'The GitHub usernames of the soup approvers to assign as reviewers'
    required: true
    default: 'nasirky'
  non-semver-dependencies:
    description: 'A list of dependencies that do not follow semantic versioning'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Copy scripts
      shell: bash
      run: cp $GITHUB_ACTION_PATH/scripts/* .
    - name: Run dependency comparison (Web)
      if: inputs.project-type != 'flutter' && inputs.project-type != 'Flutter'
      id: compare-web
      shell: bash
      run: |
        chmod +x compare_deps.sh
        result=$(./compare_deps.sh package.json "${{ inputs.non-semver-dependencies }}")
        echo "$result"
        echo "result=$(echo "$result" | tail -n 1)" >> $GITHUB_OUTPUT
    - name: Run dependency comparison (Flutter)
      if: inputs.project-type != 'web' && inputs.project-type != 'Web'
      id: compare-flutter
      shell: bash
      run: |
        chmod +x compare_deps.sh
        result=$(./compare_deps.sh pubspec.yaml "${{ inputs.non-semver-dependencies }}")
        echo "$result"
        echo "result=$(echo "$result" | tail -n 1)" >> $GITHUB_OUTPUT
    - name: Assign Reviewers
      if: ${{ steps.compare-web.outputs.result != 'nothing' && steps.compare-flutter.outputs.result != 'nothing' }}
      uses: actions/github-script@v7
      env:
        SOUP_APPROVERS: ${{ inputs.soup-approvers }}
      with:
        script: |
          const soupApprovers = process.env.SOUP_APPROVERS || "";

          const pr = context.payload.pull_request;
          if (!pr)
            core.setFailed('No pull request found.');

          const prAuthor = pr.user.login;
          const reviewerList = soupApprovers.split(',').map(r => r.trim()).filter(r => r && r !== prAuthor);

          if (reviewerList.length === 0) {
            core.info('No reviewers to assign.');
            return;
          }

          const { data: reviews } = await github.rest.pulls.listReviews({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr.number,
          });

          const approvedOrRequested = [...new Set(reviews.map(r => r.user.login))];
          const reviewersToAdd = reviewerList.filter(r => !approvedOrRequested.includes(r));

          core.info(`SOUP Approver List: ${reviewerList.join(', ')}`);
          core.info(`Already assigned reviewers: ${approvedOrRequested.join(', ')}`);

          if (reviewersToAdd.length > 0)
            core.info(`Reviewers to add: ${reviewersToAdd.join(', ')}`);

          if (reviewersToAdd.length > 0) {
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              reviewers: reviewersToAdd,
            });
            core.info(`Assigned New Reviewers: ${reviewersToAdd.join(', ')}`);
          } else {
            core.info('All SOUP Reviewers are already assigned.');
          }

    - name: Require Approval From Assigned Reviewer
      if: ${{ steps.compare-web.outputs.result != 'nothing' && steps.compare-flutter.outputs.result != 'nothing' }}
      uses: actions/github-script@v7
      env:
        SOUP_APPROVERS: ${{ inputs.soup-approvers }}
      with:
        script: |
          const soupApprovers = process.env.SOUP_APPROVERS || "";
          
          const pr = context.payload.pull_request;
          if (!pr)
            core.setFailed('No pull request found.');
          
          const prAuthor = pr.user.login;
          const reviewerList = soupApprovers.split(',').map(r => r.trim()).filter(r => r && r !== prAuthor);
          
          if (reviewerList.length === 0) {
            core.info('No reviewers to assign.');
            return;
          }

          const reviews = await github.rest.pulls.listReviews({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr.number,
          });

          const latestReviews = {};
          for (const review of reviews.data) {
            if (review.state !== "DISMISSED") {
              latestReviews[review.user.login] = review.state;
            }
          }

          const approvers = Object.entries(latestReviews)
            .filter(([user, state]) => state === 'APPROVED')
            .map(([user]) => user);

          if (approvers.length > 0)
            core.info(`Approved by: ${approvers.join(', ')}`);
          else
            core.info('No approvals yet.');

          const approved = reviewerList.some(r => latestReviews[r] === 'APPROVED');
          if (!approved)
            core.setFailed(`At least one of these reviewers must approve: ${soupApprovers}`);
          else
            core.info('Approval requirement satisfied.');
