name: 'OSV-Scanner Report'
description: 'Runs OSV-Scanner recursively on the root directory'
runs:
  using: "composite"
  steps:
      - shell: bash
        run: cp $GITHUB_ACTION_PATH/scripts/* .
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.7'
      - name: Install dependencies
        shell: bash
        run: go install github.com/google/osv-scanner/cmd/osv-scanner@latest
      - name: Run OSV-Scanner
        shell: bash
        run: osv-scanner --version
      - run: ls -ahl
        shell: bash
      - shell: bash
        run:  bash run_osv_scanner.sh
      - uses: actions/upload-artifact@v4
        with:
          name: osv-scanner-reports
          path: osv-scanner-reports
          retention-days: 90
