name: 'Setup Android'
description: 'Setting up Android & JDK'
inputs:
  key-store-file-content:
    description: ''
    required: true
  key-store-password:
    description: ''
    required: true
  signing-key-alias:
    description: ''
    required: true
  signing-key-password:
    description: ''
    required: true  
  qbs-maven-username:
    default: ""
  qbs-maven-password:
    default: ""
runs:
  using: "composite"
  steps:
    - uses: QuickBirdEng/actions/setup-environment@main
    - name: Setup Java Version
      id: setup-java
      shell: bash
      run: |
        java_version=8
        java_distribution=adopt

        # If environment variables are set, use those values 
        [[ -z $JAVA_VERSION ]] || java_version=$JAVA_VERSION 
        [[ -z $JAVA_DISTRIBUTION ]] || java_version=$JAVA_DISTRIBUTION 
        
        echo "java-version=$java_version" >> $GITHUB_OUTPUT
        echo "java-distribution=$java_distribution" >> $GITHUB_OUTPUT
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ steps.setup-java.outputs.java-version }}
        distribution: ${{ steps.setup-java.outputs.java-distribution }}
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r22
    - name: Setup Android Signing Keys
      shell: bash
      run: |
        KEY_STORE_PATH="${RUNNER_TEMP}"/keystore.jks
        echo ${{ inputs.key-store-file-content }} | base64 -di > "$KEY_STORE_PATH" 

        echo ANDROID_KEYSTORE_PATH="$KEY_STORE_PATH" >> $GITHUB_ENV
        echo ANDROID_KEYSTORE_PASSWORD=${{ inputs.key-store-password }} >> $GITHUB_ENV
        echo ANDROID_SIGNING_KEY_ALIAS=${{ inputs.signing-key-alias }} >> $GITHUB_ENV
        echo ANDROID_SIGNING_KEY_PASSWORD=${{ inputs.signing-key-password }} >> $GITHUB_ENV
    - name: Setup Maven Secrets
      if: ${{ inputs.qbs-maven-username != '' }} && ${{ inputs.qbs-maven-password != '' }}
      shell: bash
      run: |
        echo QBS_DEV_MAVEN_USERNAME=${{ inputs.qbs-maven-username }} >> $GITHUB_ENV
        echo QBS_DEV_MAVEN_PASSWORD=${{ inputs.qbs-maven-password }} >> $GITHUB_ENV