name: 'SOUP - CVE Check'
description: 'Check for known vulnerabilities in dependencies'
inputs:
  type:
    description: 'Type of package manager'
    required: true
    type: string
  package:
    description: 'Name of the package'
    required: true
    type: string
  version: 
    description: 'Version of the package to include'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Copy scripts
      shell: bash
      run: git clone git@github.com:QuickBirdEng/action-scripts.git action-scripts && mv action-scripts/* . && chmod +x cve-check.sh
    - name: CVE Check
      shell: bash
      run: bash cve-check.sh "${{ inputs.type }}" "${{ inputs.package }}" "${{ inputs.version }}"

