name: 'SOUP - Generate PDF for Approved'
description: 'Generate PDF reports for approved SOUP dependencies'

runs:
  using: "composite"
  steps:
    - name: Copy scripts
      shell: bash
      run: git clone git@github.com:QuickBirdEng/action-scripts.git action-scripts && mv action-scripts/* .
    - name: Generate PDFs
      shell: bash
      run: bash generate-pdf-for-approved-soups.sh
    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: soup_reports
        path: soup_reports
