name: 'SOUP - Generate PDF for Approved'
description: 'Generate PDF reports for approved SOUP dependencies'

runs:
  using: "composite"
  steps:
    - name: Copy scripts
      shell: bash
      run: git clone git@github.com:QuickBirdEng/action-scripts.git action-scripts && mv action-scripts/* .
    - name: Generate PDFs
      shell: bash
      run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install reportlab

          mkdir -p soup_reports
          LOG_FILE="soup_reports/_soup_report.log" 

          files=$(git ls-files '.soups/**/*.json')
          for file in $files; do
            [[ -f "$file" ]] || continue

            approval_on=$(jq -r '.metadata.approval.date // empty' "$file" 2>/dev/null || true)

            if [[ -z "$approval_on" ]]; then
              echo "❌ $file: Missing Approval" | tee -a "$LOG_FILE"
              continue
            fi

            echo "✅ $file: Approved on $approval_on" | tee -a "$LOG_FILE"

            python3 generate-soup-pdf.py "$file"
          done
    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: soup_reports
        path: soup_reports
