name: 'Web Outdated & Vulnerable Packages Report'
description: 'Generates NPM & Yarn outdated and vulnerable packages reports'
inputs:
  modules:
    description: 'Modules to check for outdated and vulnerable packages'
    required: true
    type: string
  node-version:
    description: 'Node version to use'
    type: string
    default: '18'
  reports-dir:
    description: 'Folder to store the reports'
    required: false
    default: 'reports'
runs:
  using: "composite"
  steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - shell: bash
        run: cp $GITHUB_ACTION_PATH/scripts/* .
      - shell: bash
        name: Setup yarn
        run: npm install -g yarn
      - shell: bash
        run: bash generate_reports.sh --project-path=`pwd` --reports-path=`pwd`/${{ inputs.reports-dir }} --modules=${{ inputs.modules }}
      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ${{ inputs.reports-dir }}
          retention-days: 90
