name: 'Check for SOUP changes and generate missing SOUP files'
description: 'Check for changes in dependencies and generate missing SOUP files'
inputs:
  excluded-requirements:
    description: 'A comma-separated list of requirements to exclude from SOUP generation'
    required: false
    type: string
    default: ''
  repository:
    description: 'The name of the repository (e.g., soups)'
    required: true
  gh-api-token:
    description: 'GitHub API token with repo access'
    required: true
  soup-approvers:
    description: 'List of GitHub usernames to assign as reviewers for SOUP PRs'
    required: true
  base-branch:
    description: 'The base branch to compare against (e.g., main)'
    required: true
  slack-webhook-url:
    description: 'Slack webhook URL for notifications'
    required: true
  github-to-slack-mapping:
    description: 'JSON mapping of GitHub usernames to Slack user IDs (e.g., {"github-user1":"U12345","github-user2":"U67890"})'
    required: false
runs:
  using: "composite"
  steps:
    - name: Fetch and Checkout branch
      shell: bash
      run: |
        BASE_BRANCH="${{ inputs.base-branch }}"
        BASE_BRANCH="${BASE_BRANCH#origin/}"
        git fetch --unshallow origin && git remote set-head origin --auto && git checkout ${{ github.head_ref }}
    - shell: bash
      run: git clean -fdx
    - name: Copy scripts
      shell: bash
      run: git clone -b make-own-soups-process-better git@github.com:QuickBirdEng/action-scripts.git action-scripts && mv action-scripts/* .
    - name: Generate Missing SOUPs
      env:
        EXCLUDED_REQUIREMENTS: ${{ inputs.excluded-requirements }}
      shell: bash
      run: bash soups-check.sh ${{ inputs.base-branch }}
    - name: Commit and Push Changes
      id: commit
      shell: bash
      run: |
        if ! git add .soups/**/*.json 2>/dev/null || git diff --staged --quiet; then
            echo "No changes to commit"
            echo "soup_files_generated=false" >> $GITHUB_OUTPUT
            exit 0
        fi

        USER_INFO=$(curl -s -H "Authorization: token ${{ inputs.gh-api-token }}" -H "Accept: application/vnd.github+json" https://api.github.com/user)
        EMAILS=$(curl -s -H "Authorization: token ${{ inputs.gh-api-token }}" -H "Accept: application/vnd.github+json" https://api.github.com/user/emails)
        echo "User Emails: $EMAILS"

        PR_NAME=$(echo "$USER_INFO" | jq -r .name)
        PR_EMAIL=$(echo "$EMAILS" | jq -r '.[] | select(.primary == true) | .email')

        git config --local user.email "$PR_EMAIL"
        git config --local user.name "$PR_NAME"

        git add -A .soups
        git status
        git commit  --no-verify -m "generate missing soup files"
        git push origin ${{ inputs.branch-name }}

        echo "soup_files_generated=true" >> $GITHUB_OUTPUT
  