name: 'Run Static Analysis'
description: ''

runs:
  using: "composite"
  steps:
    - name: Download sonar-scanner
      shell: bash
      run: |
        curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.1.0.4477-linux-x64.zip
        unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
    - name: Run sonar-scanner
      shell: bash
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      run: |
        $HOME/.sonar/sonar-scanner-6.1.0.4477-linux-x64/bin/sonar-scanner
