name: 'Run Static Analysis'
description: ''
inputs:
  sonar-token:
    description: 'Token for Sonarqube project'
  sonar-host-url:
    description: 'URL for the Sonarqube server'

runs:
  using: "composite"
  steps:
    - name: Download sonar-scanner
      shell: bash
      run: |
        curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.1.0.4477-linux-x64.zip
        unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
    - name: Run sonar-scanner
      shell: bash
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
      run: |
        $HOME/.sonar/sonar-scanner-6.1.0.4477-linux-x64/bin/sonar-scanner
