name: 'Build iOS App'
description: 'Building IPA for iOS applications'
inputs:
  build-number:
    description: 'Build number'
    required: true
  working-directory:
    description: 'Working directory for action'
    default: '.'
  workspace-path:
    description: 'Path to the workspace file'
    required: true
  scheme-name:
    description: 'Scheme name'
    required: true
outputs:
  artifact-path:
    description: 'The path to the xcarchive created as a result of this action'
    value: ${{ steps.build.outputs.artifact-path }}

runs:
  using: "composite"
  steps:
    - uses: QuickBirdEng/actions/setup-ios@main
    - id: build
      name: "Building IPA"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        version_and_build_number=""

        # Get tag if it exists (to get version number from it)
        if [[ $GITHUB_REF_TYPE == 'tag' ]]; then
          version=$(echo $GITHUB_REF_NAME | grep --only-matching --extended-regexp '([0-9]+).([0-9]+).([0-9]+)' | head -1)
          echo "Using Version number from tag => $version"
          version_and_build_number="$version+${{ inputs.build-number }}"
        else
          version_and_build_number="$(grep '^AS_APP_VERSION' config/iOS/xcconfig/Common.xcconfig | sed 's/version: //' | sed 's/+.*//')+${{ inputs.build-number }}"
        fi

        echo "Version & Build: $version_and_build_number"

        xcodebuild build -workspace ${{ inputs.workspace-path }} -scheme ${{ inputs.scheme-name }} -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
