name: 'Dependency Review Assignment'
description: 'Assign reviewers based on dependency changes'
inputs:
  validity-months:
    description: 'The number of months to consider for validity (e.g., 6 for 6 months).'
    required: true
    type: string
    default: '6'
runs:
  using: "composite"
  steps:
    - name: Copy scripts
      shell: bash
      run: cp $GITHUB_ACTION_PATH/scripts/* . && chmod +x versions-check.sh version-check.sh
    - shell: bash
      run: yq --version
    - name: Version Check
      shell: bash
      run: MONTHS=${{ inputs.validity-months }} bash versions-check.sh
    - name: Upload Artifacts 
      uses: actions/upload-artifact@v4
      with:
        name: versions-report
        path: versions-report.csv
        retention-days: 365

