name: 'Setup Fastlane'
description: 'Checking out and setting up fastlane'
inputs:
  platform:
    description: 'Which platform to setup for. Possible values are ios or flutter'
    default: ios
  working-directory:
    description: 'Working directory for action'
    default: '.'
  fastlane-repo:
    description: 'SSH URL for the Fastlane Repo'
    default: 'git@github.com:QuickBirdEng/fastlane.git'
runs:
  using: "composite"
  steps:
    - name: Setup Fastlane
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        cd ios
        [[ -d fastlane ]] && rm -rf fastlane
        git clone -b flutter-legacy --single-branch ${{ inputs.fastlane-repo }}
        bash fastlane/fetch_targets_and_bundle_ids.sh
