name: 'Compress & Upload Artifact to QB Spaces & (only on tags) to Release Assets'
description: 'Compress & Upload Artifact to QB Spaces'
inputs:
  repo-token:
    description: 'Github repository token (used for adding artifact to release)'
    type: string
  name:
    description: 'Output Name of the artifact'
    type: string
  name-suffix:
    description: 'Suffix to add to the end of name'
    type: string
  artifact-path:
    description: 'Path of the artifact'
    type: string
  access-key:
    description: 'Digital Ocean Access Key'
    required: true
  secret-key:
    description: 'Digital Ocean Secret Key'
    required: true
  github-token:
    description: 'Github token'
    required: false
runs:
  using: "composite"
  steps:
    - name: Generate Name for Artifact
      id: name-generator
      shell: bash
      run: |
        artifact_name="artifact"

        if [[ '${{ inputs.name }}' == '' ]]; then
          [[ '${{ github.ref_type }}' == 'tag' ]] && artifact_name="${{ github.ref_name }}"
        else
          artifact_name="${{ inputs.name }}"
        fi

        [[ '${{ inputs.name-suffix }}' == '' ]] || artifact_name="$artifact_name-${{ inputs.name-suffix }}"
        echo "artifact-name=$artifact_name" >> $GITHUB_OUTPUT
    - name: Compress XCArchive File as tar.gz
      id: compress
      uses: QuickBirdEng/actions/compress-artifact@flutter-legacy
      with:
        name: ${{ steps.name-generator.outputs.artifact-name }}
        artifact-path: ${{ inputs.artifact-path }}
    - name: Upload Artifact to QB Spaces
      uses: QuickBirdEng/actions/upload-artifact-qb@flutter-legacy
      with:
        access-key: ${{ inputs.access-key }}
        secret-key: ${{ inputs.secret-key }}
        artifact: ${{ steps.compress.outputs.artifact-path }}
    - name: Add Artifacts to Release Assets (Only for tags)
      if: ${{ github.ref_type == 'tag' }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.repo-token }}
        file: ${{ steps.compress.outputs.artifact-path }}
        asset_name: ${{ steps.name-generator.outputs.artifact-name }}.tar.gz
        tag: ${{ github.ref }}
