name: 'Checkout using SSH'
description: 'Use this action if your project uses other private repos on our Github'
inputs:
  ssh-private-key:
    description: 'The SSH key to be used for the step'
    required: true
  git-lfs:
    description: "Checkout the project with git lfs"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        lfs: git-lfs
    - uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
