name: 'Build Flutter Artifact'
description: 'Building IPA, APK or App Bundle for flutter applications'
inputs:
  build-number:
    description: 'Build number'
    required: true
  use-cache:
    description: 'Use cached version of packages (to speed up the build)'
    required: false
    default: false
  clean:
    description: 'Should perform a `flutter clean` first?'
    required: false
    default: false
  build-type:
    description: 'ipa, apk or appbundle'
    required: true
  build-arguments:
    description: 'any extra arguments such as using sksl or passing a variable using --dart-define etc.'
    required: false
  extra-step:
    description: ''
  working-directory:
    description: 'Working directory for action'
    default: '.'
  obfuscate:
    description: 'Build flutter app with obfuscation'
    required: false
    default: false

outputs:
  artifact-path:
    description: 'The path to the artifact (ipa, apk or appbundle) created by this action'
    value: ${{ steps.build-artifact.outputs.artifact-path }}
  debug-symbol-path:
    description: 'The path the the debug symbol generated by flutter build --obfuscate command'
    value: ${{ steps.build-artifact.outputs.debug-symbol-path }}
runs:
  using: "composite"
  steps:
    - uses: QuickBirdEng/actions/setup-flutter@main
      with:
        use-cache: ${{ inputs.use-cache }}
        clean: ${{ inputs.clean }}
        setup-gems: ${{ inputs.build-type == 'ipa' }}
        working-directory: ${{ inputs.working-directory }}
    - id: build-artifact
      name: "Building Artifact"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        # 1. Get version number from tag (in case a tag is pushed)
        version_number_argument=""
        # Get tag if it exists
        if [[ $GITHUB_REF_TYPE == 'tag' ]]; then
          version=$(echo $GITHUB_REF_NAME | grep --only-matching --extended-regexp '([0-9]+).([0-9]+).([0-9]+)' | head -1)
          echo "Using Version number from tag => $version"
          version_number_argument="--build-name=$version"
        fi

        # 2. Obfuscate build if enabled
        symbols_path="app_symbols"

        obfuscation_arguments=""
        if [ ${{ inputs.obfuscate }} == 'true' ]; then
          echo "Building with obfuscation enabled (symbols path: $symbols_path)"
          obfuscation_arguments="--obfuscate --split-debug-info=$symbols_path"
        fi

        # 3. Build flutter with build number and version number
        flutter build ${{ inputs.build-type }} $obfuscation_arguments --build-number=${{ inputs.build-number }} $version_number_argument ${{ inputs.build-arguments }} | tee flutter_build.log
        # 4. search for word that ends with certain strings and then remove the ending . if any and convert to relative path if needed

        artifact_path=$(cat flutter_build.log | awk '{for (word=1;word<=NF;word++) if ($word~/release.apk|release.aab|.xcarchive|.ipa/) print $word}' | sed 's/\.$//')

        case $artifact_path in
          /*) echo "artifact-path=$artifact_path" >> $GITHUB_OUTPUT ;;
          *) echo "artifact-path=${{ inputs.working-directory }}/$(echo $artifact_path)" >> $GITHUB_OUTPUT ;;
        esac

        if [ ${{ inputs.obfuscate }} == 'true' ]; then
          if [[ ${{ inputs.build-type }} == 'ipa' ]]; then
            echo "mv $symbols_path/* build/ios/archive/Runner.xcarchive/dSYMs/"
            mv $symbols_path/* build/ios/archive/Runner.xcarchive/dSYMs/
          fi
          echo "debug-symbol-path=$symbols_path" >> $GITHUB_OUTPUT
        fi
