name: 'Publish IPA to Apps@QuickBird and TestFlight (conditions apply)'
description: 'Publishing Flutter iOS builds'
inputs:
  upload-key:
    description: 'upload-key'
    required: true
  publish-to-testflight:
    description: 'Should publish to Testflight?'
    default: false
  match-repository:
    description: 'Match Repository'
    required: true
  match-password:
    description: 'Password for Match Repo'
    required: true
  match-apple-id:
    description: 'Apple ID to use for match'
    required: true
  match-apple-team-id:
    description: 'Apple Team ID to use for match'
    required: true
  match-keychain-password:
    description: 'Keychain Password to use for match'
    required: true
  apple-auth-key-id:
    description: 'Auth Key'
    required: true
  apple-auth-key-issuer-id:
    description: 'Auth Key Issuer ID'
    required: true
  apple-auth-key-content:
    description: 'Auth Key Content'
    required: true
  apple-auth-key-encoding:
    description: 'Auth Key Encoding'
    required: true
  name-suffix:
    description: 'Suffix to add to the end of branch/tag name'
    type: string
    default: ''
  working-directory:
    description: 'Working directory for action'
    default: '.'
  build-number:
    description: 'Build Number'
    type: string
  slack-slug:
    description: 'The part of slack hook url after services/'
    required: true
  release-notes:
    description: 'Release Notes. Only used for flutter applications'
    type: string
    required: false
  submit-for-review:
    description: 'Submit TestFlight Build for Review'
    type: boolean
    default: false
    required: false
  build-arguments:
    description: 'Build Arguments'
    type: string
    required: false
    default: ''
  obfuscate:
    description: 'Should obfuscate dart code?'
    required: false
    default: false
outputs:
  artifact-path:
    description: 'The path to the ipa created by this action'
    value: ${{ steps.build-ipa.outputs.ipa-path }}
  flutter-artifact-path:
    description: 'The path to the xcarchive created by this action'
    value: ${{ steps.build.outputs.artifact-path }}
  artifact-dsyms-path:
    description: 'The path to the dsyms file'
    value: ${{ steps.build.outputs.artifact-path }}/dSYMs
  artifact-dart-symbols-file-path:
    description: 'The path to the dart symbols file'
    value: ${{ steps.build.outputs.artifact-dart-symbols-file-path }}

runs:
  using: "composite"
  steps:
    - uses: QuickBirdEng/actions/setup-ios@main
    - uses: QuickBirdEng/actions/setup-fastlane@dart-obfuscation
      with:
        platform: flutter
        working-directory: ${{ inputs.working-directory }}
    - uses: QuickBirdEng/actions/setup-fastlane-environment@main
      with:
        match-repository: ${{ inputs.match-repository }}
        match-password: ${{ inputs.match-password }}
        match-apple-id: ${{ inputs.match-apple-id }}
        match-apple-team-id: ${{ inputs.match-apple-team-id }}
        match-keychain-password: ${{ inputs.match-keychain-password }}
        apple-auth-key-id: ${{ inputs.apple-auth-key-id }}
        apple-auth-key-issuer-id: ${{ inputs.apple-auth-key-issuer-id }}
        apple-auth-key-content: ${{ inputs.apple-auth-key-content }}
        apple-auth-key-encoding: ${{ inputs.apple-auth-key-encoding }}
        build-number: ${{ inputs.build-number }}
        slack-slug: ${{ inputs.slack-slug }}
        release-notes: ${{ inputs.release-notes }}
        submit-for-review: ${{ inputs.submit-for-review }}
    - uses: QuickBirdEng/actions/setup-flutter@dart-obfuscation
      with:
        use-cache: ${{ inputs.use-cache }}
        clean: true
        setup-gems: true
        working-directory: ${{ inputs.working-directory }}
    - shell: bash -l {0}
      working-directory: ${{ inputs.working-directory }}/ios
      run: bundle exec fastlane prepare_for_release type:appstore
    - uses: QuickBirdEng/actions/flutter-build@dart-obfuscation
      id: build
      with:
        build-type: ipa
        build-number: ${{ inputs.build-number }}
        build-arguments: ${{ inputs.build-arguments }}
        clean: true
        working-directory: ${{ inputs.working-directory }}
        obfuscate: ${{ inputs.obfuscate }}
        skip-setup-step: true
    - name: Publish to TestFlight
      shell: bash -l {0}
      if: ${{ inputs.publish-to-testflight == 'true' }}
      working-directory: ${{ inputs.working-directory }}/ios
      run: bundle exec fastlane releaseToTestFlight xcarchive_path:${{steps.build.outputs.artifact-path}}
    - name: Prepare for Upload to apps.quickbirdstudios.com
      id: build-ipa
      shell: bash -l {0}
      working-directory: ${{ inputs.working-directory }}/ios
      run: |
        set -eo pipefail && bundle exec fastlane generate_ipa type:adhoc xcarchive_path:${{steps.build.outputs.artifact-path}} | tee fastlane.log
        ipa_path=$(cat fastlane.log | grep -o '\IPA Path => .*' | sed -e 's/IPA Path => //g')
        echo "ipa-path=$ipa_path" >> $GITHUB_OUTPUT
    - name: "Publishing to apps.quickbirdstudios.com"
      uses: QuickBirdEng/actions/qb-publish@dart-obfuscation
      with:
        upload-key: ${{ inputs.upload-key }}
        file: ${{ steps.build-ipa.outputs.ipa-path }}
        name-suffix: ${{ github.event.inputs.name-suffix == '' && '' || format('-{0}', github.event.inputs.name-suffix) }}
