name: 'Publish Android APK to Apps@QuickBird'
description: 'Building IPA, APK or App Bundle for flutter applications'
inputs:
  build-number:
    description: 'Build number'
    required: true
  use-cache:
    description: 'Use cached version of packages (to speed up the build)'
    required: false
    default: true
  clean:
    description: 'Should perform a `flutter clean` first?'
    required: false
    default: false
  build-arguments:
    description: 'any extra arguments such as using sksl or passing a variable using --dart-define etc.'
    required: false
  upload-key:
    description: 'upload-key'
    required: true
  key-store-file-content:
    description: ''
    required: true
  key-store-password:
    description: ''
    required: true
  signing-key-alias:
    description: ''
    required: true
  signing-key-password:
    description: ''
    required: true
  qbs-maven-username:
    description: 'Needed if the project uses a private artifact from QBS Maven'
    required: false
  qbs-maven-password:
    description: 'Needed if the project uses a private artifact from QBS Maven'
    required: false
  name-suffix:
    description: 'Suffix to add to the end of branch/tag name'
    type: string
    default: ''
  working-directory:
    description: 'Working directory for action'
    default: '.'
outputs:
  artifact-path:
    description: 'The path to the apk created by this action'
    value: ${{ steps.build.outputs.artifact-path }}
  artifact-version-and-build-number:
    description: 'The version and build number of the artifact'
    value: ${{ steps.build.outputs.artifact-version-and-build-number }}
  artifact-dart-symbols-file-path:
    description: 'The path to the dart symbols file'
    value: ${{ steps.build.outputs.artifact-dart-symbols-file-path }}

runs:
  using: "composite"
  steps:
    - uses: QuickBirdEng/actions/setup-android@main
      with:
        key-store-file-content: ${{ inputs.key-store-file-content }}
        key-store-password: ${{ inputs.key-store-password }}
        signing-key-alias: ${{ inputs.signing-key-alias }}
        signing-key-password: ${{ inputs.signing-key-password }}
        qbs-maven-username: ${{ inputs.qbs-maven-username }}
        qbs-maven-password: ${{ inputs.qbs-maven-password }}
    - uses: QuickBirdEng/actions/flutter-build@dart-obfuscation
      id: build
      with:
        clean: ${{ inputs.clean }}
        build-number: ${{ inputs.build-number }}
        build-arguments: ${{ inputs.build-arguments }}
        build-type: apk
        use-cache: ${{ inputs.use-cache }}
        working-directory: ${{ inputs.working-directory }}
    - name: "Publishing to apps.quickbirdstudios.com"
      uses: QuickBirdEng/actions/qb-publish@main
      with:
        upload-key: ${{ inputs.upload-key }}
        file: ${{ steps.build.outputs.artifact-path }}
        name-suffix: ${{ github.event.inputs.name-suffix == '' && '' || format('-{0}', github.event.inputs.name-suffix) }}
