name: 'Upload debug symbols to sentry'
description: 'Upload debug symbols to sentry'
inputs:
  url:
    description: 'Url of the sentry server (in case of a custom one)'
    required: false
  project:
    description: 'Name of the project in sentry'
    required: false
  auth-token:
    description: 'Authorization token for sentry'
    required: false
  organization:
    description: 'Organization name'
    required: false
    default: ''
  dsyms-path:
    description: 'The path to the dsYMs folder'
    required: false
    default: ''
  proguard-mapping-file-path:
    description: 'The path to the proguard mapping file'
    required: false
    default: ''
  dart-symbols-file-path:
    description: 'The path to the dart symbols file'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install CLI
      shell: bash
      run: npm install -g @sentry/cli
    - name: Sentry CLI Version
      shell: bash
      run: sentry-cli --version
    - name: Upload Dart Symbols
      if: ${{ inputs.dart-symbols-file-path != '' }}
      shell: bash
      run: |
        sentry-cli --url ${{inputs.url}} upload-dif ${{ inputs.dart-symbols-file-path }} --auth-token ${{inputs.auth-token}} --org ${{inputs.organization}} --project ${{inputs.project}} || true
    - name: Upload Debug Symbols (iOS)
      if: ${{ inputs.dsyms-path != '' }}
      shell: bash
      run: |
        sentry-cli --url ${{inputs.url}} debug-files upload ${{inputs.dsyms-path}} --auth-token ${{inputs.auth-token}} --org ${{inputs.organization}} --project ${{inputs.project}} || true
    - name: Upload Proguard Mapping (Android)
      if: ${{ inputs.proguard-mapping-file-path != '' }}
      shell: bash
      run: |
        sentry-cli --url ${{inputs.url}} upload-proguard ${{inputs.proguard-mapping-file-path}} --auth-token ${{inputs.auth-token}} --org ${{inputs.organization}} --project ${{inputs.project}} || true
