name: 'Setup iOS'
description: 'Setting up Environment before every action'
inputs:
  platform:
    description: 'Which platform to setup for. Possible values are ios or flutter'
    default: ios
  working-directory:
    description: 'Working directory for action'
    default: '.'
  use-cache:
    description: 'Use cached version of packages (to speed up the build)'
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - uses: QuickBirdEng/actions/setup-environment@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
    - name: Setup Ruby Environment
      shell: bash
      run: eval "$(rbenv init -)"
    - uses: QuickBirdEng/actions/setup-fastlane@main
      with:
        platform: ${{ inputs.platform }}
        working-directory: ${{ inputs.working-directory }}