name: 'Setup iOS'
description: 'Setting up Environment before every action'
inputs:
  use-cache:
    description: 'Use cached version of packages (to speed up the build)'
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - uses: QuickBirdEng/actions/setup-environment@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
    # - name: Set up Ruby
    #   uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
    #   with:
    #     ruby-version: ${{ env.RUBY_VERSION }}
    #     bundler-cache: true