name: 'Setup iOS'
description: 'Setting up Environment before every action'
inputs:
  use-cache:
    description: 'Use cached version of packages (to speed up the build)'
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - uses: QuickBirdEng/actions/setup-environment@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
    - name: Setup Ruby Environment
      shell: bash
      run: eval "$(rbenv init -)"
    - name: Setup Build Path
      shell: bash
      run: |
        path=`pwd`
        path=${path%%_work*}_work
        echo "DERIVED_DATA_PATH=$path/DerivedData" >> $GITHUB_ENV
        echo "FLUTTER_XCODE_DERIVED_DATA_PATH=$path/DerivedData" >> $GITHUB_ENV
        echo "FLUTTER_XCODE_TEMP_ROOT=$path/DerivedData" >> $GITHUB_ENV
        echo "ARCHIVE_PATH=$path/Archives" >> $GITHUB_ENV
        echo "BUILD_LOG_PATH=$path/FastlaneLogs" >> $GITHUB_ENV
        echo "GEM_HOME=$path/gems" >> $GITHUB_ENV
