name: 'Upload Artifact to QB DO Space'
description: 'Upload Artifact to QB DO Space'
inputs:
  access-key:
    description: 'Digital Ocean Access Key'
    required: true
  secret-key:
    description: 'Digital Ocean Secret Key'
    required: true
  artifact:
    description: 'Path of the artifact'
    required: true
  space-name:
    description: 'Digital Ocean Space name'
    required: false
    default: 'quickbird-artifacts'
  space-region:
    description: 'Digital Ocean Space region'
    required: false
    default: 'fra1'

runs:
  using: "composite"
  steps:
    - name: 'Upload as artifact'
      shell: bash
      run: |
        s3cmd put "${{ inputs.artifact }}" \
          "s3://${{ inputs.space-name }}/${{ github.event.repository.name }}/" \
          --access_key="${{ inputs.access-key }}" \
          --secret_key="${{ inputs.secret-key }}" \
          --host="${{ inputs.space-region }}.digitaloceanspaces.com" \
          --host-bucket="%(bucket)s.${{ inputs.space-region }}.digitaloceanspaces.com"
